version: '3'
services:
  recipes-frontend:
    container_name: recipes-frontend
    build:
      context: .
      dockerfile: recipe-browser-web/Dockerfile
    ports:
      - "37920:80"
    depends_on:
      - recipes-backend

  recipes-backend:
    container_name: recipes-backend
    build:
      context: .
      dockerfile: recipe-server-backend/Dockerfile
    volumes:
      - ./recipe-server-backend/cards:/usr/share/nginx/html/cards
      - ./recipe-server-backend/images-small:/usr/share/nginx/html/images/small
      - ./recipe-server-backend/images-large:/usr/share/nginx/html/images/large
